spring:
  application:
    name: catboardback
  datasource:
    url: jdbc:mariadb://localhost:3306/catdb
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

boardImgLocation: C:/Users/codehows/Documents/GitHub/CatBoardBack/board
